feat: move usage and api to typedocs
poolifier/poolifier pull request #811
Opened 2023-08-05 11:18 UTC by namandeep-123

## PR Checklist

- [ ] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] If your changes contain any new feature please be sure to document it.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add an entry to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

Add toggle to general guidelines and move usage and api to typedocs md file.

2023-08-06 17:05 UTC, jerome-benoit requested changes

2023-08-06 21:07 UTC, namandeep-123 commented on README.md
> +[**Quick start**](docs/getting-started.md)
So I've done all the changes; now should I move the general guidelines to the guidelines.md file? and put back usage info in the readme.md file?

2023-08-07 20:25 UTC, namandeep-123 commented on README.md
> +[**Quick start**](docs/getting-started.md)
Done.

2023-08-08 18:56 UTC, jerome-benoit approved these changes

2023-08-08 18:56 UTC, merged